out_dir: "./results/ffhq65k_testing"
seed: 42

models:
    generator:
            name: "AGGV3"
            config:
                embed: 4
            

    discrimnator:




train:
    name: "inpainting"
    batch_size: 32
    num_work: 16
    config:
        data_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/testing/imgs"
        prior_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/testing/edges"
        mask_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/testing/mask"
        mask_config:
                  mask_mode: "external"
                  root:
        data_len: -1
        image_size: [256, 256]
        is_train: True

val:
    name: "inpainting"
    batch_size: 1
    num_work: 2
    config:
        data_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/testing/imgs"
        prior_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/testing/edges"
        mask_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/testing/mask"
        mask_config:
                  mask_mode: "external"
                  root:
        data_len: 400
        image_size: [256, 256]
        is_train: False


optim:
    lr_g: 0.00005
    lr_d: 0.000005
    b1: 0.5
    b2: 0.9
  
eval_inter: 5
resume: 0
epoch: 150
save_model: 10
sample_inter: 1
