out_dir: "./results/celeba_V3"
seed: 42

models:
    generator:
            name: "AGGV3"
            config:
                embed: 4
            

    discrimnator:


gpu : 1

train:
    name: "inpainting"
    batch_size: 32
    num_work: 16
    config:
        data_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/training/imgs"
        prior_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/training/edges"
        mask_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/training/mask"
        mask_config:
                  mask_mode: "external"
                  root:
        data_len: -1
        image_size: [256, 256]
        is_train: True

val:
    name: "inpainting"
    batch_size: 1
    num_work: 2
    config:
        data_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/testing/imgs"
        prior_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/testing/edges"
        mask_root: "/mnt/recsys/daniel/datasets/journalpaper/ffhq_65k/testing/mask"
        mask_config:
                  mask_mode: "external"
                  root:
        data_len: 400
        image_size: [256, 256]
        is_train: False


optim:
    lr_g: 0.00005
    lr_d: 0.000005
    b1: 0.5
    b2: 0.9
  
eval_inter: 1
resume: 0
epoch: 150
save_model: 1
sample_inter: 1

model_ex:
  layers: [3, 4, 6, 3]
  pretrained: True
  path: ~
  output_dim: 1024
  heads: 32

model_d:
  input_nc: 4
  ndf: 64
  semantic_dim: 1024
  semantic_size: 16
  use_bias: True
  nheads: 1
  dhead: 64